on: workflow_dispatch
jobs:
  reset-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Reset branches
        run: |
          git push -f origin e9f0123:feature/outdated
