on: workflow_dispatch
jobs:
  reset-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Reset branches
        run: |
          git push -f origin 6a2ed8d2db15cb0100d80ef22ba270313b8fd3ca:feature/outdated
