on:
  - workflow_dispatch
  - pull_request


jobs:
  verify-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Git Tools
        uses: PrincipleStudios/scalable-git-branching-tools-installer-action@latest
      - run: |
          git-verify-updated.ps1 -target ${{ github.head_ref }}
